Repository gillout/book-store, pull requests merged in 2020-11, with the labels that each got.

#6 Refact : Modifie la configuration de la base de donnée
  .gitignore
  public/index.php
  src/app/App.php
  src/app/back/controller/BookController.php
  src/app/config/config.php
  src/app/config/config.sample.php
  src/app/router/Router.php
Labels: enhancement

#8 Refact : Transforme le formulaire pour gérer les 3 boutons
  public/script/book-form.js
  src/app/back/view/template.php
Labels: enhancement, refactor

#10 Fix: Corrige l'erreur 'Maximum function nesting level' lié à l'appel récursif du constructeur App
  .gitignore
  composer.json
  public/index.php
  public/script/book-form.js
  public/style.css
  src/app/App.php
  src/app/back/controller/BookController.php
  src/app/back/manager/BookManager.php
  src/app/back/model/Book.php
  src/app/back/view/all.php
  src/app/back/view/template.php
  src/app/bookstore.sql
  src/app/config/config.php
  src/app/config/config.sample.php
  src/app/router/Router.php
Labels: fix

#9 Feat : Ajoute la possibilité de modifier un livre
  public/index.php
  src/app/App.php
  src/app/back/controller/BookController.php
  src/app/back/manager/BookManager.php
  src/app/back/view/list.php
  src/app/back/view/template.php
  src/app/router/Router.php
Labels: feature
